project:
  type: website

website:
  title: "Automações Cruz | Desenvolvimento de Software e Automações"

  navbar:
    left:
      - href: index.qmd
        text: Início

      - href: portfolio.qmd
        text: Projetos

      - href: about.qmd
        text: Sobre

  page-footer:
    left: "© 2026 Automações Cruz. Todos os direitos reservados."
    right: "CNPJ: 66.076.509/0001-26"

format:
  html:
    theme: flatly
    css: styles.css