project:
  type: website

website:
  title: "Automações Cruz"

  navbar:
    left:
      - href: index.qmd
        text: Início

      - href: portfolio.qmd
        text: Projetos

      - href: about.qmd
        text: Sobre

  page-footer:
    left: "© 2026 Automações Cruz. Todos os direitos reservados."

format:
  html:
    theme: flatly
    css: styles.css